### ISSUE TITLE
コア機能作成

### ISSUE THREAD

**Issue by rino7tech** [Unity1week-3-18-3-24/Unity1weekRS#1]
やること(コア機能)
・キャラクター操作(ジャンプ)
・カメラ追従
・ゲームオーバー・クリア判定
・(地面すり抜け)

**Comment by ushou2005** [comment]
どこまで進んだー？

**Comment by ushou2005** [comment]
別のところに完了報告あったわw
やることとやったこと同じIssueに書いていただけると助かります
