### ISSUE TITLE
寝る前開発

### ISSUE THREAD

**Issue by rino7tech** [Unity1week-3-18-3-24/Unity1weekRS#10]
やること
・ダメージ受けたら点滅して一定時間ダメージ受けない
・落下ダメージ
・Ready GO!!入れる
・ゴール地点で動きを止める（段々）

**Comment by rino7tech** [comment]
レイヤー変えても反応しちゃうよーー；；
一旦お風呂行く1時間後再開します

**Comment by ushou2005** [comment]
えーまじか

**Comment by rino7tech** [comment]
粘ります頑張って解決する！

**Comment by ushou2005** [comment]
あまり無理しないようにな。どうしても無理なら違うことやるという手があることも忘れないでね！

**Comment by rino7tech** [comment]
ありがと！詰まったら一旦違うタスクします！！！！

**Comment by rino7tech** [comment]
諦めて明日の自分に託します
早起きしてこのタスク消化します！
寝る！おやすみ！

**Comment by rino7tech** [comment]
なんか寝れなかったので続きやります

**Comment by rino7tech** [comment]
Ready GO!!入れれました！

**Comment by rino7tech** [comment]
コメントアウトいっぱい書きました！
ゴール地点で動き止めれました！(徐々には出来てない)

**Comment by rino7tech** [comment]
落下の処理やってます！
いつ寝落ちするかわかんないので定期的にちゃんとcommitします

**Comment by rino7tech** [comment]
終わりませんでした！寝る！
結局
・Ready GO!!入れた
・ゴール地点で動き止めた（徐々には出来てない）
が完全に終わりました
残り起きたらやりまする

**Comment by ushou2005** [comment]
お疲れ様！こっちでもチャレンジしてみる！

**Comment by rino7tech** [comment]
続きやり！ま！す！

**Comment by rino7tech** [comment]
ジャンプの2回できないようにできた！わーい！

**Comment by rino7tech** [comment]
ダメージ受けたら点滅して一定時間ダメージ受けないやつできた！びっくり！！

**Comment by ushou2005** [comment]
マジ？！流石すぎる！

**Comment by rino7tech** [comment]
クリア演出できました

**Comment by ushou2005** [comment]
あれやることほぼ終わった？

**Comment by rino7tech** [comment]
今ゲームオーバーのやつ作ってる！
それ終わったら終わったかもしんないっす、、！

**Comment by ushou2005** [comment]
まじで...？俺がキャンプ行って帰って寝てる間に？早くない？

**Comment by rino7tech** [comment]
なんか楽しくなってたら出来ました👍🏻

**Comment by rino7tech** [comment]
でもまだデザイン入れたりとか出来てないからまだまだです‼️

**Comment by ushou2005** [comment]
早く作りますすいませんでした...

**Comment by rino7tech** [comment]
終わった！
