### ISSUE TITLE
タスクいっぱい嬉しい開発

### ISSUE THREAD

**Issue by rino7tech** [Unity1week-3-18-3-24/Unity1weekRS#13]
寝るまでのやることあとで決めてコメントに書いときます
タスクいっぱいでるんるんですありがとうしょう

**Comment by ushou2005** [comment]
なんか特殊な癖持った人みたい...笑
頼みました！一度に全部やらなくて大丈夫やで！

**Comment by rino7tech** [comment]
さっきまでだらだらしまくってましたすいません
今からやります

やること
・ランダムなキー全部被らんくできるように
・スクロールのスピード早くなる

**Comment by rino7tech** [comment]
謎の体力減らないのもなおす

**Comment by rino7tech** [comment]
ランダムなキーに機能つけれるようになりました

**Comment by rino7tech** [comment]
全部できた！！！！

**Comment by ushou2005** [comment]
ないす！！
