### ISSUE TITLE
寝起き開発です

### ISSUE THREAD

**Issue by rino7tech** [Unity1week-3-18-3-24/Unity1weekRS#9]
やること
・コメントアウト文字化け直す
・障害物処理
・体力ゲージ

**Comment by rino7tech** [comment]
MacのUnityのVSCodeとか諸々の環境設定につまづきまくってます

**Comment by rino7tech** [comment]
遊んでたりしたので今更ようやく環境構築できました
Sliderのエラーusing UnityEngine.UI　入れたら治りました

**Comment by ushou2005** [comment]
あ、それ忘れてたわ。バカじゃん俺
エラー修正ありがとうございます

**Comment by rino7tech** [comment]
なんかジャンプ効かなくなっててえぐーーー
原因調べます〜〜

**Comment by rino7tech** [comment]
PlayerControllerのBarrierScriptがbarrierオブジェクトを消しちゃうとMissingになっちゃうからSetActiveをfalseにして擬似的に消してます
Destroyの方がよかったら戻してください！

**Comment by rino7tech** [comment]
まじでOnCollisionStayとAddforceの相性悪すぎてえぐい
実装方法変えた方がいいね

**Comment by ushou2005** [comment]
> PlayerControllerのBarrierScriptがbarrierオブジェクトを消しちゃうとMissingになっちゃうからSetActiveをfalseにして擬似的に消してます Destroyの方がよかったら戻してください！

これもうちょっと詳しく聞きたい。これってどんな不都合があるん？

**Comment by rino7tech** [comment]
<img width="349" alt="スクリーンショット 2024-03-20 20 33 20" src="https://github.com/Unity1week-3-18-3-24/Unity1weekRS/assets/156809496/bc90ae97-e5c6-49b8-bd72-50f43b218cc9">
障害物が消えたらこうなる！
別にこれのせいで何か起こるっていうことではないけどMissing良くないと思うから一応ってこと！

**Comment by ushou2005** [comment]
あ、ごめん
それダメージ判定作ってる時に作ったけど使わずにおわったやつやと思う。
消しておいていただけると助かります

**Comment by rino7tech** [comment]
スクリプトごと消しちゃっていい感じ？

**Comment by ushou2005** [comment]
型定義したスクリプトだけね！確かそれなくても動くはず

**Comment by rino7tech** [comment]
おけです〜〜！動いた！

**Comment by ushou2005** [comment]
全部解決したそうなのでクローズします
